version: '3.8'
name: smartphone-bookings
services:
  postgresql:
    image: postgres:16.1-alpine
    container_name: postgresql-smartphone-bookings
    environment:
      POSTGRES_USER: smartphone
      POSTGRES_PASSWORD: bookings
      POSTGRES_DB: smartphone_bookings
    volumes:
      - "./smartphone-bookings/postgresql/:/var/lib/postgresql/data"
      - ./initdb.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U smartphone -d smartphone_bookings" ]
      interval: 10s
      timeout: 5s
      retries: 5

  booking-server:
    build:
      context: ../booking-server/target/
      dockerfile_inline: |
        FROM openjdk:17-jdk-alpine
        COPY booking-server-0.1.0-uber.jar /app.jar
        ENTRYPOINT ["java","-jar","/app.jar"]
    container_name: booking-server
    depends_on:
      - postgresql
    links:
      - "postgresql:db"
    environment:
      DB_URL: jdbc:postgresql://db:5432/smartphone_bookings?user=smartphone&password=bookings
    ports:
      - "8080:8080"

