package dym.interview.fonoapi

/**
 * @author dym
 */
data class SmartphoneSpecs(
    val manufacturer: String,
    val model: String,
    val technology: String,
    val bands2g: String,
    val bands3g: String,
    val bands4g: String,
    val bands5g: String
) {

    companion object {

        fun getSmartphoneSpecs(manufacturer: String, model: String): SmartphoneSpecs? {
            return specs[manufacturer]?.get(model)
        }

        // A smartphone database generated by extra-terrestrial intelligence.
        // It is not in the actual database, because it is not in the scope of the booking system.
        // It should not even exist, but it does, because FonoAPI is down.
        private val specs = mapOf(
            "Samsung" to mapOf(
                "Galaxy S9" to SmartphoneSpecs(
                    manufacturer = "Samsung",
                    model = "Galaxy S9",
                    technology = "GSM / CDMA / HSPA / EVDO / LTE / 5G",
                    bands2g = "GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)",
                    bands3g = "HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100",
                    bands4g = "1, 2, 3, 4, 5, 7, 8, 12, 13, 14, 17, 18, 19, 20, 25, 26, 28, 29, 30, 38, 39, 40, 41, 46, 48, 66, 71 - SM-G960U1",
                    bands5g = "2, 5, 41, 66, 71, 260, 261 SA/NSA/Sub6/mmWave - SM-G960U1"
                ),
                "Galaxy S8" to SmartphoneSpecs(
                    manufacturer = "Samsung",
                    model = "Galaxy S8",
                    technology = "GSM / CDMA / HSPA / EVDO / LTE / 5G",
                    bands2g = "GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)",
                    bands3g = "HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100",
                    bands4g = "1, 2, 3, 4, 5, 7, 8, 12, 13, 14, 17, 18, 19, 20, 25, 26, 28, 29, 30, 38, 39, 40, 41, 46, 48, 66, 71 - SM-G960U1",
                    bands5g = "2, 5, 41, 66, 71, 260, 261 SA/NSA/Sub6/mmWave - SM-G960U1"
                )
            ),
            "Motorola" to mapOf(
                "Nexus 6" to SmartphoneSpecs(
                    manufacturer = "Motorola",
                    model = "Nexus 6",
                    technology = "GSM / CDMA / HSPA / EVDO / LTE / 5G",
                    bands2g = "GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)",
                    bands3g = "HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100",
                    bands4g = "1, 2, 3, 4, 5, 7, 8, 12, 13, 14, 17, 18, 19, 20, 25, 26, 28, 29, 30, 38, 39, 40, 41, 46, 48, 66, 71 - SM-G960U1",
                    bands5g = "2, 5, 41, 66, 71, 260, 261 SA/NSA/Sub6/mmWave - SM-G960U1"
                )
            ),
            "Oneplus" to mapOf(
                "9" to SmartphoneSpecs(
                    manufacturer = "Oneplus",
                    model = "9",
                    technology = "GSM / CDMA / HSPA / EVDO / LTE / 5G",
                    bands2g = "GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)",
                    bands3g = "HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100",
                    bands4g = "1, 2, 3, 4, 5, 7, 8, 12, 13, 14, 17, 18, 19, 20, 25, 26, 28, 29, 30, 38, 39, 40, 41, 46, 48, 66, 71 - SM-G960U1",
                    bands5g = "2, 5, 41, 66, 71, 260, 261 SA/NSA/Sub6/mmWave - SM-G960U1"
                )
            ),
            "Apple" to mapOf(
                "iPhone 13" to SmartphoneSpecs(
                    manufacturer = "Apple",
                    model = "iPhone 13",
                    technology = "GSM / CDMA / HSPA / EVDO / LTE / 5G",
                    bands2g = "GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)",
                    bands3g = "HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100",
                    bands4g = "1, 2, 3, 4, 5, 7, 8, 12, 13, 14, 17, 18, 19, 20, 25, 26, 28, 29, 30, 38, 39, 40, 41, 46, 48, 66, 71 - SM-G960U1",
                    bands5g = "2, 5, 41, 66, 71, 260, 261 SA/NSA/Sub6/mmWave - SM-G960U1"
                ),
                "iPhone 12" to SmartphoneSpecs(
                    manufacturer = "Apple",
                    model = "iPhone 12",
                    technology = "GSM / CDMA / HSPA / EVDO / LTE / 5G",
                    bands2g = "GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)",
                    bands3g = "HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100",
                    bands4g = "1, 2, 3, 4, 5, 7, 8, 12, 13, 14, 17, 18, 19, 20, 25, 26, 28, 29, 30, 38, 39, 40, 41, 46, 48, 66, 71 - SM-G960U1",
                    bands5g = "2, 5, 41, 66, 71, 260, 261 SA/NSA/Sub6/mmWave - SM-G960U1"
                ),
                "iPhone 11" to SmartphoneSpecs(
                    manufacturer = "Apple",
                    model = "iPhone 11",
                    technology = "GSM / CDMA / HSPA / EVDO / LTE / 5G",
                    bands2g = "GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)",
                    bands3g = "HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100",
                    bands4g = "1, 2, 3, 4, 5, 7, 8, 12, 13, 14, 17, 18, 19, 20, 25, 26, 28, 29, 30, 38, 39, 40, 41, 46, 48, 66, 71 - SM-G960U1",
                    bands5g = "2, 5, 41, 66, 71, 260, 261 SA/NSA/Sub6/mmWave - SM-G960U1"
                ),
                "iPhone X" to SmartphoneSpecs(
                    manufacturer = "Apple",
                    model = "iPhone X",
                    technology = "GSM / CDMA / HSPA / EVDO / LTE / 5G",
                    bands2g = "GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)",
                    bands3g = "HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100",
                    bands4g = "1, 2, 3, 4, 5, 7, 8, 12, 13, 14, 17, 18, 19, 20, 25, 26, 28, 29, 30, 38, 39, 40, 41, 46, 48, 66, 71 - SM-G960U1",
                    bands5g = "2, 5, 41, 66, 71, 260, 261 SA/NSA/Sub6/mmWave - SM-G960U1"
                )
            ),
            "Nokia" to mapOf(
                "3310" to SmartphoneSpecs(
                    manufacturer = "Nokia",
                    model = "3310",
                    technology = "GSM / CDMA / HSPA / EVDO / LTE / 5G",
                    bands2g = "GSM 850 / 900 / 1800 / 1900 - SIM 1 & SIM 2 (dual-SIM model only)",
                    bands3g = "HSDPA 850 / 900 / 1700(AWS) / 1900 / 2100",
                    bands4g = "1, 2, 3, 4, 5, 7, 8, 12, 13, 14, 17, 18, 19, 20, 25, 26, 28, 29, 30, 38, 39, 40, 41, 46, 48, 66, 71 - SM-G960U1",
                    bands5g = "2, 5, 41, 66, 71, 260, 261 SA/NSA/Sub6/mmWave - SM-G960U1"
                )
            )
        )
    }
}
